version: "3.8"

services:
  # Microservicio de Vehicles
  vehicles_api:
    build:
      context: ./APIS/vehicles
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/vehiculos_db?schema=public"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Microservicio de Fichas
  fichas_api:
    build:
      context: ./APIS/fichas
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/vehiculos_db?schema=public"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Microservicio de Users
  users_api:
    build:
      context: ./APIS/users
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/vehiculos_db?schema=public"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # API Gateway
  api_gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - vehicles_api
      - fichas_api
      - users_api
    environment:
      NODE_ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres_audit
    container_name: postgres
    environment:
      POSTGRES_DB: vehiculos_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_logs/postgresql:/var/log/postgresql
      - ./postgresql_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # pgAdmin (opcional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./logs/pgadmin:/var/log/pgadmin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
